// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[Table("Branch")]
public partial class Branch
{
    [Key]
    [Column("Branch_No")]
    public int BranchNo { get; set; }

    [Required]
    [Column("Branch_Name")]
    [StringLength(255)]
    [Unicode(false)]
    public string BranchName { get; set; }

    [Column("Branch_Phone")]
    [StringLength(11)]
    [Unicode(false)]
    public string BranchPhone { get; set; }

    [Required]
    [Column("Branch_City")]
    [StringLength(255)]
    [Unicode(false)]
    public string BranchCity { get; set; }

    [Required]
    [Column("Branch_Street")]
    [StringLength(255)]
    [Unicode(false)]
    public string BranchStreet { get; set; }

    [InverseProperty("BranchNoNavigation")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
}