// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[Table("Department")]
public partial class Department
{
    [Key]
    [Column("Department_Id")]
    public int DepartmentId { get; set; }

    [Required]
    [Column("Department_Name")]
    [StringLength(255)]
    [Unicode(false)]
    public string DepartmentName { get; set; }

    [Column("Department_Desc")]
    [StringLength(255)]
    [Unicode(false)]
    public string DepartmentDesc { get; set; }

    [Column("Branch_No")]
    public int BranchNo { get; set; }

    [Column("Manager_Id")]
    public int? ManagerId { get; set; }

    [ForeignKey("BranchNo")]
    [InverseProperty("Departments")]
    public virtual Branch BranchNoNavigation { get; set; }

    [InverseProperty("Department")]
    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    [ForeignKey("ManagerId")]
    [InverseProperty("Departments")]
    public virtual Instructor Manager { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Track> Tracks { get; set; } = new List<Track>();
}