// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[Table("Exam")]
public partial class Exam
{
    [Key]
    [Column("Exam_Id")]
    public int ExamId { get; set; }

    [Column("Exam_StartTime")]
    [Precision(0)]
    public TimeOnly ExamStartTime { get; set; }

    [Column("Exam_StartDate")]
    public DateOnly ExamStartDate { get; set; }

    [Column("Exam_Duration")]
    public double ExamDuration { get; set; }

    [Column("Exam_TotalPoints")]
    public int ExamTotalPoints { get; set; }

    [Column("Course_Id")]
    public int? CourseId { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("Exams")]
    public virtual Course Course { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<StudentAnswer> StudentAnswers { get; set; } = new List<StudentAnswer>();
}