// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_Form.Models
{
    public partial class GetExamQuestionsWithChoices_updatedResult
    {
        [StringLength(255)]
        public string Question_Head { get; set; }
        [StringLength(8000)]
        public string Question_Options { get; set; }
    }
}
