// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_Form.Models
{
    public partial class GetStudentsByDepartmentResult
    {
        [StringLength(255)]
        public string Student_Name { get; set; }
        [StringLength(11)]
        public string Student_Phone { get; set; }
        [StringLength(50)]
        public string Student_Email { get; set; }
        [StringLength(255)]
        public string Department_Name { get; set; }
        [StringLength(255)]
        public string Track_Name { get; set; }
    }
}
