// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_Form.Models
{
    public partial class GetStudentCoursesAndExamsResult
    {
        [StringLength(255)]
        public string Course_Name { get; set; }
        public int Exam_Id { get; set; }
        public TimeOnly Exam_StartTime { get; set; }
        public DateOnly Exam_StartDate { get; set; }
        public double Exam_Duration { get; set; }
        public int Exam_TotalPoints { get; set; }
        public int? Course_Id { get; set; }
    }
}
