// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[Table("Instructor")]
[Index("InstructorEmail", Name = "Instructor_Email", IsUnique = true)]
public partial class Instructor
{
    [Key]
    [Column("Instructor_Id")]
    public int InstructorId { get; set; }

    [Required]
    [Column("Instructor_Name")]
    [StringLength(255)]
    [Unicode(false)]
    public string InstructorName { get; set; }

    [Column("Instructor_Phone")]
    [StringLength(11)]
    [Unicode(false)]
    public string InstructorPhone { get; set; }

    [Required]
    [Column("Instructor_City")]
    [StringLength(255)]
    [Unicode(false)]
    public string InstructorCity { get; set; }

    [Required]
    [Column("Instructor_Street")]
    [StringLength(255)]
    [Unicode(false)]
    public string InstructorStreet { get; set; }

    [Column("Instructor_DOB")]
    public DateOnly InstructorDob { get; set; }

    [Required]
    [Column("Instructor_Gender")]
    [StringLength(10)]
    [Unicode(false)]
    public string InstructorGender { get; set; }

    [Required]
    [Column("Instructor_Degree")]
    [StringLength(255)]
    [Unicode(false)]
    public string InstructorDegree { get; set; }

    [Column("Instructor_Salary", TypeName = "money")]
    public decimal InstructorSalary { get; set; }

    [Required]
    [Column("Instructor_Email")]
    [StringLength(50)]
    [Unicode(false)]
    public string InstructorEmail { get; set; }

    [Column("Department_Id")]
    public int DepartmentId { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("Instructors")]
    public virtual Department Department { get; set; }

    [InverseProperty("Manager")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    [ForeignKey("InstructorEmail")]
    [InverseProperty("Instructor")]
    public virtual User InstructorEmailNavigation { get; set; }

    [ForeignKey("InstructorId")]
    [InverseProperty("Instructors")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}