// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[Table("Question")]
public partial class Question
{
    [Key]
    [Column("Question_Id")]
    public int QuestionId { get; set; }

    [Required]
    [Column("Question_Head")]
    [StringLength(255)]
    [Unicode(false)]
    public string QuestionHead { get; set; }

    [Required]
    [Column("Question_Type")]
    [StringLength(50)]
    [Unicode(false)]
    public string QuestionType { get; set; }

    [Required]
    [Column("Question_Answer")]
    [StringLength(255)]
    [Unicode(false)]
    public string QuestionAnswer { get; set; }

    [Column("Question_Points")]
    public int QuestionPoints { get; set; }

    [Column("Course_Id")]
    public int CourseId { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("Questions")]
    public virtual Course Course { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<QuestionOption> QuestionOptions { get; set; } = new List<QuestionOption>();

    [InverseProperty("Question")]
    public virtual ICollection<StudentAnswer> StudentAnswers { get; set; } = new List<StudentAnswer>();
}