// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[PrimaryKey("QuestionId", "QuestionOption1")]
[Table("Question_Options")]
public partial class QuestionOption
{
    [Key]
    [Column("Question_Id")]
    public int QuestionId { get; set; }

    [Key]
    [Column("Question_Option")]
    [StringLength(255)]
    [Unicode(false)]
    public string QuestionOption1 { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("QuestionOptions")]
    public virtual Question Question { get; set; }
}