// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[PrimaryKey("StudentId", "ExamId", "QuestionId")]
[Table("Student_Answer")]
public partial class StudentAnswer
{
    [Key]
    [Column("Student_Id")]
    public int StudentId { get; set; }

    [Key]
    [Column("Exam_Id")]
    public int ExamId { get; set; }

    [Key]
    [Column("Question_Id")]
    public int QuestionId { get; set; }

    [Column("Student_Ans")]
    [StringLength(255)]
    [Unicode(false)]
    public string StudentAns { get; set; }

    [Column("Student_Que_Grade")]
    public int? StudentQueGrade { get; set; }

    [ForeignKey("ExamId")]
    [InverseProperty("StudentAnswers")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("StudentAnswers")]
    public virtual Question Question { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("StudentAnswers")]
    public virtual Student Student { get; set; }
}