// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[PrimaryKey("CourseId", "StudentId")]
[Table("Student_Course")]
public partial class StudentCourse
{
    [Key]
    [Column("Course_Id")]
    public int CourseId { get; set; }

    [Key]
    [Column("Student_Id")]
    public int StudentId { get; set; }

    [Column("Student_Course_Grade")]
    public int? StudentCourseGrade { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("StudentCourses")]
    public virtual Course Course { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("StudentCourses")]
    public virtual Student Student { get; set; }
}