// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[Table("Student")]
[Index("StudentEmail", Name = "Student_Email", IsUnique = true)]
public partial class Student
{
    [Key]
    [Column("Student_Id")]
    public int StudentId { get; set; }

    [Required]
    [Column("Student_Name")]
    [StringLength(255)]
    [Unicode(false)]
    public string StudentName { get; set; }

    [Column("Student_Phone")]
    [StringLength(11)]
    [Unicode(false)]
    public string StudentPhone { get; set; }

    [Required]
    [Column("Student_City")]
    [StringLength(255)]
    [Unicode(false)]
    public string StudentCity { get; set; }

    [Required]
    [Column("Student_Street")]
    [StringLength(255)]
    [Unicode(false)]
    public string StudentStreet { get; set; }

    [Column("Student_DOB")]
    public DateOnly StudentDob { get; set; }

    [Required]
    [Column("Student_Email")]
    [StringLength(50)]
    [Unicode(false)]
    public string StudentEmail { get; set; }

    [Required]
    [Column("Student_Gender")]
    [StringLength(10)]
    [Unicode(false)]
    public string StudentGender { get; set; }

    [Column("Track_Id")]
    public int? TrackId { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<StudentAnswer> StudentAnswers { get; set; } = new List<StudentAnswer>();

    [InverseProperty("Student")]
    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new List<StudentCourse>();

    [ForeignKey("StudentEmail")]
    [InverseProperty("Student")]
    public virtual User StudentEmailNavigation { get; set; }

    [ForeignKey("TrackId")]
    [InverseProperty("Students")]
    public virtual Track Track { get; set; }
}