// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[Table("Track")]
public partial class Track
{
    [Key]
    [Column("Track_Id")]
    public int TrackId { get; set; }

    [Required]
    [Column("Track_Name")]
    [StringLength(255)]
    [Unicode(false)]
    public string TrackName { get; set; }

    [Column("Track_Desc")]
    [StringLength(255)]
    [Unicode(false)]
    public string TrackDesc { get; set; }

    [Column("Dept_Id")]
    public int DeptId { get; set; }

    [ForeignKey("DeptId")]
    [InverseProperty("Tracks")]
    public virtual Department Dept { get; set; }

    [InverseProperty("Track")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}