// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_Form.Models;

[PrimaryKey("UserName", "Password", "Email")]
[Index("Email", Name = "User_Email", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("User_Name")]
    [StringLength(255)]
    [Unicode(false)]
    public string UserName { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; }

    [Required]
    [Column("User_Type")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserType { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [InverseProperty("InstructorEmailNavigation")]
    public virtual Instructor Instructor { get; set; }

    [InverseProperty("StudentEmailNavigation")]
    public virtual Student Student { get; set; }
}